_target_: src.models.HatefulMemesUniter

embedding_dim: 768
backbone_output_dim: 1000
language_feature_dim: 128
vision_feature_dim: 128
fusion_output_size: 128
model_type: concat_bert
dropout_p: 0.25
lr: 0.00001