_target_: src.datamodules.SemiHatefulMemesDataModuleBERT

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 64
train_val_test_split: [800, 100, 100]
num_workers: 0
pin_memory: False
num_labeled: 100
